add year built to TOPA_ssl data set
NeighborhoodInfoDC/PresCat pull request #370
Opened 2023-05-18 14:40 UTC by eburton9

@ptatian I decided it was best to add the year built vars to the TOPA_ssl dataset that we created in the first prog as I couldn't match the cama_parcel dataset to the TOPA_database because the TOPA_database has multiple SSLs. I'm doing the # of units and ward in the match_notice prog but need this one to batch submit before I finish that prog up to incorpoate the years built.

2023-05-18 15:05 UTC, ptatian commented
Thanks, @eburton9 I'll take a look. 

Did you create an issue for this? I forgot to mention that. It may seem a little unnecessary, but I'd like us to be in the habit of creating an issue when working on a new task.

2023-05-22 21:11 UTC, ptatian requested changes
@eburton9 Sorry for being slow to get back to you, but this looks good. You don't need the Proc Sort for Realprop.cama_parcel and I recommend deleting it. Please also update the revisions message to summarize the changes being made to the data set. 

`%let revisions = Add u_date_dhcd_received_ta_reg.;`

I added a Proc Sort to remove duplicate SSLs from TOPA_SSL. I don't think this was affecting anything, but since this data set is supposed to just be a list of parcels it's cleaner to take out the duplicates. 

For awareness, Rob [updated many of the Realprop data sets](file://sas1/DCData/Metadata/meta_updates.html) last week. This will change some of the results compared to what we ran previously. Hard to predict how, but if you see differences in the data that could be the reason. 

Thanks!

2023-05-23 18:40 UTC, eburton9 commented
@ptatian Thanks, Peter! With the %let revisions I only added AYB and EYB to the Topa_ssl dataset so should I just update the revisions section for topa_ssl in the finalize data set at the bottom rather than the global let revisions at the top?

2023-05-23 20:21 UTC, ptatian commented
That's right, but since the program updates all the data sets, I'd change the global %let statement. You can say that the two variables are only being added to Topa_ssl.

2023-05-24 15:22 UTC, eburton9 commented
@ptatian Great, I updated that now. Let me know if I'm good to merge and batch submit to move on to edits in the TOPA match notices program.

2023-05-24 15:48 UTC, ptatian approved these changes

2023-05-24 15:48 UTC, ptatian commented on Prog/TOPA/TOPA_data_to_DC_data.sas
> +%let revisions = Add u_date_dhcd_received_ta_reg. add AYB. and EYB. to Topa_ssl;
@eburton9 Once you make that small change, you can go ahead and merge. Thanks!

2023-05-24 17:37 UTC, eburton9 commented on Prog/TOPA/TOPA_data_to_DC_data.sas
> +%let revisions = Add u_date_dhcd_received_ta_reg. add AYB. and EYB. to Topa_ssl;
@ptatian ooh interesting and good to know, thanks!

2023-05-24 17:37 UTC, merged