Update #442
NeighborhoodInfoDC/PresCat pull request #446
Opened 2024-01-18 20:43 UTC by dharvey17

@ptatian ready for review

In my previous note, I'd confused creating the HUD files with this step (hence the comment about the Update-#)

2024-01-18 21:31 UTC, ptatian requested changes
Hi Donovan. Looks good. Asking that you delete the Update_Sec8mf_2023_11.sas program and see if any of the nonmatching projects in the REAC data are in the Catalog. Thanks!

2024-01-18 21:31 UTC, ptatian commented on Prog/Updates/Update_Sec8mf_2023_11.sas
This program doesn't have any parameters filled in. But we don't need to run earlier downloads if we missed them earlier. We can just run the 2024_01 file. So we can delete this program.

2024-01-18 21:31 UTC, ptatian commented on Prog/Updates/Update_REAC_2023_11.sas
In the listing output for the REAC program, there is a list of "Nonmatching REAC records" Can you please check to see if any of these are projects in the Catalog? If so, you can update the Macros\Update_REAC_init.sas program to add the correspondence between the REAC_ID and the Catalog NLIHC_ID.

2024-01-18 21:31 UTC, ptatian commented on Prog/Updates/Update_Sec8mf_2024_01.sas
Looks good!

2024-01-26 21:40 UTC, dharvey17 commented
List of non-matching properties

- The Foundry Lofts
- City Market at O Street
- The Lexington at Market Square
- Arbor View Apartments
- Indigo Apartments 
- The Griffin Apartments
- Zen Apollo

2024-01-30 15:10 UTC, dharvey17 commented
Hi Peter, I thought I tagged you in case you wanted to take a look at the changes you flagged.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: Peter Tatian ***@***.***>
Sent: Tuesday, January 30, 2024 8:56:27 AM
To: NeighborhoodInfoDC/PresCat ***@***.***>
Cc: Harvey, Donovan ***@***.***>; Mention ***@***.***>
Subject: Re: [NeighborhoodInfoDC/PresCat] Update #442 (PR #446)


[EXTERNAL]


Hi @dharvey17<https://github.com/dharvey17> Just checking...is this ready for me to take a second look?

—
Reply to this email directly, view it on GitHub<https://github.com/NeighborhoodInfoDC/PresCat/pull/446#issuecomment-1917073045>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AXAGRZNB3AKYAW6DZWKLBJ3YRECZXAVCNFSM6AAAAABCA45AX6VHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTSMJXGA3TGMBUGU>.
You are receiving this because you were mentioned.Message ID: ***@***.***>

2024-01-30 15:11 UTC, ptatian commented
Yes, that's fine. I just didn't know if you were finished. I'll review now.

2024-01-30 15:15 UTC, ptatian approved these changes
Thanks, @dharvey17 OK to merge and do the final batch submit.

2024-01-31 14:25 UTC, merged